spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:rss_feed_test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: h2
    generated-ddl: false
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
    h2:
      console:
        enabled: true
        path: /h2-console

app:
  version: v1

scheduler:
  feed: 30000

url:
  feed: https://feeds.simplecast.com/54nAGcIl